[server]
enableStaticServing = true
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = false
toolbarMode = "viewer"

[theme]
base = "light"
primaryColor = "#86cc85"
